# Auto-curated ordinary prose negatives for U2 export. No slang.
NEGATIVES = (
    "The committee approved the budget amendment.",
    "Water boils at one hundred degrees Celsius.",
    "Please find the attached invoice for March.",
    "The museum opens at ten on weekdays.",
    "Photosynthesis converts light into chemical energy.",
    "The train to Sacramento leaves from platform two.",
    "This warranty covers defects in materials.",
    "Average rainfall in July was two inches.",
    "The library card expires in December.",
    "Sodium chloride is table salt.",
    "The board meeting is scheduled for Tuesday.",
    "A rectangle has four right angles.",
    "Please confirm receipt of this shipment.",
    "The periodic table lists the elements.",
    "Oak trees drop acorns in autumn.",
    "The speed limit on this road is twenty five.",
    "This paragraph contains no slang tokens.",
    "The recipe calls for two cups of flour.",
    "Latitude and longitude specify a point.",
    "The contract is governed by California law.",
    "Mercury is the closest planet to the Sun.",
    "The river flows south toward the delta.",
    "Please submit the application by Friday noon.",
    "Cotton fabric shrinks slightly when washed in hot water.",
    "The auditorium seats approximately four hundred people.",
    "Nitrogen makes up most of Earth's atmosphere.",
    "The post office closes at five on Saturdays.",
    "A hexagon has six equal sides when regular.",
    "The printer needs a new toner cartridge.",
    "Mountains form where tectonic plates collide.",
    "Please keep the aisle clear during boarding.",
    "The calendar marks the equinox in March.",
    "Stainless steel resists rust under normal use.",
    "The encyclopedia volume covers letters M through O.",
    "Evaporation increases on warm dry days.",
    "The ferry crosses the bay every half hour.",
    "A kilogram equals one thousand grams.",
    "Please sign on the line above your printed name.",
    "The orchard yields apples in early September.",
    "Sound travels slower than light in air.",
    "The classroom whiteboard uses dry erase markers.",
    "Granite is a common igneous rock.",
    "Please return overdue books to the front desk.",
    "The compass needle points toward magnetic north.",
    "Yeast causes bread dough to rise.",
    "The highway rest area has drinking water.",
    "A century contains one hundred years.",
    "Please wear closed toe shoes in the laboratory.",
    "The archive stores microfilm of old newspapers.",
    "Condensation forms on cold glass surfaces.",
    "The soccer field measures about one hundred meters.",
    "Aluminum conducts heat and electricity well.",
    "Please update your mailing address online.",
    "The tide chart shows high water at dawn.",
    "Birds migrate south before winter arrives.",
    "The thermostat is set to twenty two degrees.",
    "Paper is typically made from wood pulp.",
    "Please fasten your seat belt before departure.",
    "The dictionary defines ordinary words clearly.",
    "Clay hardens when fired in a kiln.",
    "The bus route serves downtown and the airport.",
    "Vitamin C is found in citrus fruit.",
    "Please label each sample with the date.",
    "The glacier advances slowly down the valley.",
    "Concrete cures over several days after pouring.",
    "The flashlight requires two AA batteries.",
    "Roots absorb water from the soil.",
    "Please schedule the inspection for next week.",
    "The piano has eighty eight keys.",
    "Copper wires carry household electric current.",
    "The hiking trail begins at the ranger station.",
    "Salt melts ice on cold roadways.",
    "Please file the report in chronological order.",
    "The telescope reveals craters on the Moon.",
    "Wool garments should be washed gently.",
    "The dam regulates water for irrigation.",
    "A triangle's angles sum to one hundred eighty degrees.",
    "Please store chemicals in the labeled cabinet.",
    "The lighthouse warns ships near the reef.",
    "Bees pollinate many flowering plants.",
    "The elevator serves floors one through twelve.",
    "Ink dries quickly on absorbent paper.",
    "Please verify the serial number on the device.",
    "The prairie grasses bend in strong wind.",
    "Glass expands slightly when heated.",
    "The census counts residents every ten years.",
    "Maple syrup is boiled from tree sap.",
    "Please keep receipts for tax records.",
    "The volcano emitted ash last century.",
    "Rubber tires grip wet pavement better when new.",
    "The aquarium filters water continuously.",
    "Seeds need moisture and warmth to germinate.",
    "Please arrive fifteen minutes before the appointment.",
    "The cathedral spire is visible from the square.",
    "Iron oxidizes when exposed to moisture.",
    "The newsletter is published on the first Monday.",
    "Clouds form when moist air cools.",
    "Please use the crosswalk at the intersection.",
    "The museum exhibit explains local geology.",
    "Bamboo grows rapidly in warm climates.",
    "The wrench fits a fourteen millimeter bolt.",
    "Ice floats because it is less dense than liquid water.",
    "Please photocopy both sides of the form.",
    "The orchard irrigation runs before sunrise.",
    "Quartz is a hard mineral common in sand.",
    "The cafeteria serves lunch until two o'clock.",
    "Friction converts motion into heat.",
    "Please replace the air filter every six months.",
    "The meadow floods after heavy spring rain.",
    "Silver tarnishes when exposed to sulfur compounds.",
    "The lecture hall has tiered seating.",
    "Photosynthesis occurs mainly in plant leaves.",
    "Please dial nine for an outside line.",
    "The reservoir supplies drinking water to the city.",
    "Limestone dissolves slowly in acidic rain.",
    "The bicycle path parallels the riverbank.",
    "Acceleration is the rate of change of velocity.",
    "Please stack the chairs after the meeting.",
    "The greenhouse maintains a steady temperature.",
    "Coral reefs support diverse marine life.",
    "The stapler holds twenty sheets of paper.",
    "Dew forms overnight on cool grass.",
    "Please initial each page of the agreement.",
    "The canyon walls show layered sedimentary rock.",
    "Zinc coating protects steel from corrosion.",
    "The waiting room has magazines and water.",
    "Osmosis moves water across a membrane.",
    "Please extinguish campfires completely before leaving.",
    "The peninsula juts into the northern bay.",
    "Nylon fabric is strong and lightweight.",
    "The index lists topics alphabetically.",
    "Magnets attract objects containing iron.",
    "Please rinse the beaker with distilled water.",
    "The plateau rises above the surrounding plain.",
    "Cedar wood resists many insect pests.",
    "The stopwatch measures elapsed time precisely.",
    "Evaporated milk is concentrated by removing water.",
    "Please keep noise low in the reading room.",
    "The estuary mixes fresh and salt water.",
    "Porcelain dishes are fired at high temperature.",
    "The appendix contains supplementary tables.",
    "Inertia keeps moving objects in motion.",
    "Please unlock the cabinet with the master key.",
    "The savanna has scattered trees and tall grass.",
    "Brass is an alloy of copper and zinc.",
    "The projector displays slides on the screen.",
    "Capillaries connect arteries to veins.",
    "Please shred outdated confidential documents.",
    "The fjord was carved by ancient glaciers.",
    "Cottonseed oil is used in some foods.",
    "The barcode identifies the product uniquely.",
    "Reflection sends light back from a mirror.",
    "Please water the seedlings every other day.",
    "The bluff overlooks the winding river.",
    "Tin cans are often lined to prevent reactions.",
    "The syllabus outlines weekly reading assignments.",
    "Diffusion spreads particles from high to low concentration.",
    "Please park only in marked spaces.",
    "The tundra remains cold for most of the year.",
    "Plywood is made from layered wood veneers.",
    "The metronome keeps a steady musical tempo.",
    "Condensation nuclei help clouds form.",
    "Please copy the agenda for all attendees.",
    "The archipelago includes dozens of small islands.",
    "Solder joins metal parts with a low melting alloy.",
    "The footnote cites the original publication year.",
    "Torque tends to cause rotation about an axis.",
    "Please calibrate the scale before weighing samples.",
    "The dune shifts gradually with prevailing winds.",
    "Hemp fiber is used in some textiles and rope.",
    "The abstract summarizes the paper in one paragraph.",
    "Viscosity measures a fluid's resistance to flow.",
    "Please keep flammable liquids in approved containers.",
    "The mesa has a flat top and steep sides.",
    "Asphalt softens in extreme summer heat.",
    "The glossary defines technical terms used herein.",
    "Refraction bends light as it enters water.",
    "Please confirm the guest count by Wednesday.",
    "The wetland filters runoff before it reaches the lake.",
    "Ceramic tiles are common in kitchen floors.",
    "The bibliography lists all referenced works.",
    "Momentum equals mass times velocity.",
    "Please wipe the lab bench after each experiment.",
    "The ridge separates two drainage basins.",
    "Linseed oil is used in some wood finishes.",
    "The preface explains the book's purpose.",
    "Frequency is measured in hertz.",
    "Please store dried goods in airtight jars.",
    "The delta forms where the river meets the sea.",
    "Marble is metamorphic rock from limestone.",
    "The table of contents lists chapter titles.",
    "Pressure equals force divided by area.",
    "Please keep the fire extinguisher accessible.",
    "The foothills rise gently toward the mountains.",
    "Shellac is a natural resin finish for wood.",
    "The errata sheet corrects printing mistakes.",
    "Wavelength is the distance between wave peaks.",
    "Please label leftovers with the preparation date.",
    "The isthmus connects two larger land masses.",
    "Turpentine thins some oil based paints.",
    "The colophon states the printer and date.",
    "Density is mass per unit volume.",
    "Please recycle cardboard in the blue bin.",
    "The atoll encircles a shallow lagoon.",
    "Beeswax is used in candles and polish.",
    "The dedication page names the author's family.",
    "Gravity pulls objects toward Earth's center.",
    "Please close windows before the storm arrives.",
)
